package Visual;

import Codigo.Tabela_Chat;
import Codigo.cod_chat;
import Codigo.Adc_palavra;
import java.awt.event.KeyEvent;
import java.nio.charset.Charset;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrio Nunes
 */
public class ChatBoot extends javax.swing.JFrame {

    /**
     * Creates new form ChatBoot
     */
    public ChatBoot() {
        initComponents();
        t.carregarTabelaChat();
        resp.append("Robot   > Ola Meu nome e Robot, em que posso ajudar ? \n");
        resp.setEditable(false);
        perg.requestFocus();
        resp.setLineWrap(true);
    }

    Tabela_Chat t = new Tabela_Chat();
    cod_chat c = new cod_chat();
    Adc_palavra p = new Adc_palavra();
    
    public void adc() {
        p.setRes(JOptionPane.showInputDialog(null, "Robot   > Poderia me dizer a resposta dessa pergunta: " + p.getPer() + " \n"));
        new cod_chat().adc(p.getPer(), p.getRes());
        t.carregarTabelaChat();
        resp.append("Robot   > Obrigado por ter me ensinado \n");
    }

    public void conversa() {
        String descricao = perg.getText();
        c = t.consultarPergunta(descricao);
        if (c == null) {
            resp.append("Usuario > " + perg.getText() + "\n");
            resp.append("Robot   > Nao sei responder, poderia me ensinar? Por favor diga SIM \n");
            p.setPer(descricao);
        } else if ("nao".equalsIgnoreCase(descricao)) {
            resp.append("Usuario > " + perg.getText() + "\n");
            resp.append("Robot   > Voce nao me ensino entao nao sei responder \n");
        } else if ("sim".equalsIgnoreCase(descricao)) {
            adc();
        } else {
            resp.append("Usuario > " + perg.getText() + "\n");
            resp.append("Robot   > " + c.getResposta() + "\n");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        resp = new javax.swing.JTextArea();
        perg = new javax.swing.JTextField();
        enviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resp.setColumns(20);
        resp.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        resp.setRows(5);
        jScrollPane1.setViewportView(resp);

        perg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pergKeyPressed(evt);
            }
        });

        enviar.setText("ENVIAR");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(perg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enviar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pergKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pergKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            conversa();
            perg.setText("");
        }
    }//GEN-LAST:event_pergKeyPressed

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        conversa();
        perg.setText("");
    }//GEN-LAST:event_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatBoot.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatBoot.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatBoot.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatBoot.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatBoot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviar;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField perg;
    private javax.swing.JTextArea resp;
    // End of variables declaration//GEN-END:variables
}
